#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFL_DebugUtils

#include "Basic.hpp"

#include "BPFL_DebugUtils_classes.hpp"
#include "BPFL_DebugUtils_parameters.hpp"


namespace SDK
{

// Function BPFL_DebugUtils.BPFL_DebugUtils_C.PrintProperty
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           PropName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class FString                           Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// struct FLinearColor                     TextColor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           CallFunc_Concat_StrStr_ReturnValue                     (ZeroConstructor, HasGetValueTypeHash)
// class FString                           CallFunc_Concat_StrStr_ReturnValue_1                   (ZeroConstructor, HasGetValueTypeHash)

void UBPFL_DebugUtils_C::PrintProperty(const class FString& PropName, const class FString& Value, const struct FLinearColor& TextColor, class UObject* __WorldContext, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_DebugUtils_C", "PrintProperty");

	Params::BPFL_DebugUtils_C_PrintProperty Parms{};

	Parms.PropName = std::move(PropName);
	Parms.Value = std::move(Value);
	Parms.TextColor = std::move(TextColor);
	Parms.__WorldContext = __WorldContext;
	Parms.CallFunc_Concat_StrStr_ReturnValue = std::move(CallFunc_Concat_StrStr_ReturnValue);
	Parms.CallFunc_Concat_StrStr_ReturnValue_1 = std::move(CallFunc_Concat_StrStr_ReturnValue_1);

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BPFL_DebugUtils.BPFL_DebugUtils_C.PrintStr
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Name                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class FString                           Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// struct FLinearColor                     TextColor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPFL_DebugUtils_C::PrintStr(const class FString& Name, const class FString& Value, const struct FLinearColor& TextColor, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_DebugUtils_C", "PrintStr");

	Params::BPFL_DebugUtils_C_PrintStr Parms{};

	Parms.Name = std::move(Name);
	Parms.Value = std::move(Value);
	Parms.TextColor = std::move(TextColor);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BPFL_DebugUtils.BPFL_DebugUtils_C.PrintBool
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Name                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// bool                                    bInBool                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FLinearColor                     TextColor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           CallFunc_Conv_BoolToString_ReturnValue                 (ZeroConstructor, HasGetValueTypeHash)

void UBPFL_DebugUtils_C::PrintBool(const class FString& Name, bool bInBool, const struct FLinearColor& TextColor, class UObject* __WorldContext, const class FString& CallFunc_Conv_BoolToString_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_DebugUtils_C", "PrintBool");

	Params::BPFL_DebugUtils_C_PrintBool Parms{};

	Parms.Name = std::move(Name);
	Parms.bInBool = bInBool;
	Parms.TextColor = std::move(TextColor);
	Parms.__WorldContext = __WorldContext;
	Parms.CallFunc_Conv_BoolToString_ReturnValue = std::move(CallFunc_Conv_BoolToString_ReturnValue);

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BPFL_DebugUtils.BPFL_DebugUtils_C.PrintInt
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Name                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int32                                   InInteger                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     TextColor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           CallFunc_Conv_IntToString_ReturnValue                  (ZeroConstructor, HasGetValueTypeHash)

void UBPFL_DebugUtils_C::PrintInt(const class FString& Name, int32 InInteger, const struct FLinearColor& TextColor, class UObject* __WorldContext, const class FString& CallFunc_Conv_IntToString_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_DebugUtils_C", "PrintInt");

	Params::BPFL_DebugUtils_C_PrintInt Parms{};

	Parms.Name = std::move(Name);
	Parms.InInteger = InInteger;
	Parms.TextColor = std::move(TextColor);
	Parms.__WorldContext = __WorldContext;
	Parms.CallFunc_Conv_IntToString_ReturnValue = std::move(CallFunc_Conv_IntToString_ReturnValue);

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BPFL_DebugUtils.BPFL_DebugUtils_C.PrintFloat
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Name                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// float                                   InFloat                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     TextColor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           CallFunc_Conv_FloatToString_ReturnValue                (ZeroConstructor, HasGetValueTypeHash)

void UBPFL_DebugUtils_C::PrintFloat(const class FString& Name, float InFloat, const struct FLinearColor& TextColor, class UObject* __WorldContext, const class FString& CallFunc_Conv_FloatToString_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_DebugUtils_C", "PrintFloat");

	Params::BPFL_DebugUtils_C_PrintFloat Parms{};

	Parms.Name = std::move(Name);
	Parms.InFloat = InFloat;
	Parms.TextColor = std::move(TextColor);
	Parms.__WorldContext = __WorldContext;
	Parms.CallFunc_Conv_FloatToString_ReturnValue = std::move(CallFunc_Conv_FloatToString_ReturnValue);

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}

}

