#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFL_HDWeapon

#include "Basic.hpp"

#include "DonkehFramework_structs.hpp"
#include "HDMain_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPFL_HDWeapon.BPFL_HDWeapon_C
// 0x0000 (0x0028 - 0x0028)
class UBPFL_HDWeapon_C final  : public UBlueprintFunctionLibrary
{
public:
	static void FireModeToString(enum class EFireMode FireMode, class UObject* __WorldContext, class FString* ModeString, enum class EFireMode Temp_byte_Variable, const class FString& Temp_string_Variable, const class FString& Temp_string_Variable_1, const class FString& Temp_string_Variable_2, const class FString& K2Node_Select_Default);
	static void FireModeToDisplayText(enum class EFireMode FireMode, class UObject* __WorldContext, class FText* ModeText, enum class EFireMode Temp_byte_Variable, class FText Temp_text_Variable, class FText Temp_text_Variable_1, class FText Temp_text_Variable_2, class FText K2Node_Select_Default);
	static void AimStyleToDisplayText(enum class EHDWeaponAimStyle AimStyle, class UObject* __WorldContext, class FText* StyleText, enum class EHDWeaponAimStyle Temp_byte_Variable, class FText Temp_text_Variable, class FText Temp_text_Variable_1, class FText Temp_text_Variable_2, class FText Temp_text_Variable_3, class FText Temp_text_Variable_4, class FText K2Node_Select_Default);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"BPFL_HDWeapon_C">();
	}
	static class UBPFL_HDWeapon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPFL_HDWeapon_C>();
	}
};

}

