#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CS_SuppressionShake

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CS_SuppressionShake.CS_SuppressionShake_C
// 0x0000 (0x0160 - 0x0160)
class UCS_SuppressionShake_C final  : public UCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"CS_SuppressionShake_C">();
	}
	static class UCS_SuppressionShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCS_SuppressionShake_C>();
	}
};

}

