#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FEntitlementBadgeUIDefinition

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "FEntitlementDefinition_structs.hpp"


namespace SDK
{

// UserDefinedStruct FEntitlementBadgeUIDefinition.FEntitlementBadgeUIDefinition
// 0x0098 (0x0098 - 0x0000)
struct FFEntitlementBadgeUIDefinition final 
{
public:
	struct FSlateBrush                            Icon_2_CF5F88F845329D7B7884FAAA929513D7;           // 0x0000(0x0088)(Edit, BlueprintVisible)
	TArray<struct FFEntitlementDefinition>        Entitlements_20_EBFD21A24AC78F2267FB5C946C532D63;  // 0x0088(0x0010)(Edit, BlueprintVisible, HasGetValueTypeHash)
};

}

