#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OWIEnhancedVehicleMovement

#include "Basic.hpp"


namespace SDK::Params
{

// Function OWIEnhancedVehicleMovement.WheeledVehicleMovementComponentTank.SetBothTracksThrottleInput
// 0x0004 (0x0004 - 0x0000)
struct WheeledVehicleMovementComponentTank_SetBothTracksThrottleInput final 
{
public:
	float                                         InThrottle;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function OWIEnhancedVehicleMovement.WheeledVehicleMovementComponentTank.SetLeftTrackThrottleInput
// 0x0004 (0x0004 - 0x0000)
struct WheeledVehicleMovementComponentTank_SetLeftTrackThrottleInput final 
{
public:
	float                                         InThrottle;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function OWIEnhancedVehicleMovement.WheeledVehicleMovementComponentTank.SetRightTrackThrottleInput
// 0x0004 (0x0004 - 0x0000)
struct WheeledVehicleMovementComponentTank_SetRightTrackThrottleInput final 
{
public:
	float                                         InThrottle;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function OWIEnhancedVehicleMovement.WheeledVehicleMovementComponentTank.GetLeftTrackSpeed
// 0x0004 (0x0004 - 0x0000)
struct WheeledVehicleMovementComponentTank_GetLeftTrackSpeed final 
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function OWIEnhancedVehicleMovement.WheeledVehicleMovementComponentTank.GetRightTrackSpeed
// 0x0004 (0x0004 - 0x0000)
struct WheeledVehicleMovementComponentTank_GetRightTrackSpeed final 
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

