#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Checkbox

#include "Basic.hpp"

#include "WBP_Checkbox_classes.hpp"
#include "WBP_Checkbox_parameters.hpp"


namespace SDK
{

// Function WBP_Checkbox.WBP_Checkbox_C.CheckStateChanged__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// enum class ECheckBoxState               CheckedState                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Checkbox_C::CheckStateChanged__DelegateSignature(enum class ECheckBoxState CheckedState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Checkbox_C", "CheckStateChanged__DelegateSignature");

	Params::WBP_Checkbox_C_CheckStateChanged__DelegateSignature Parms{};

	Parms.CheckedState = CheckedState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Checkbox.WBP_Checkbox_C.CheckStateChangedBool__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bChecked                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Checkbox_C::CheckStateChangedBool__DelegateSignature(bool bChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Checkbox_C", "CheckStateChangedBool__DelegateSignature");

	Params::WBP_Checkbox_C_CheckStateChangedBool__DelegateSignature Parms{};

	Parms.bChecked = bChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Checkbox.WBP_Checkbox_C.ExecuteUbergraph_WBP_Checkbox
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// enum class ECheckBoxState               CallFunc_GetCheckedState_ReturnValue                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_ComponentBoundEvent_bIsChecked                  (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Checkbox_C::ExecuteUbergraph_WBP_Checkbox(int32 EntryPoint, enum class ECheckBoxState CallFunc_GetCheckedState_ReturnValue, bool K2Node_ComponentBoundEvent_bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Checkbox_C", "ExecuteUbergraph_WBP_Checkbox");

	Params::WBP_Checkbox_C_ExecuteUbergraph_WBP_Checkbox Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.CallFunc_GetCheckedState_ReturnValue = CallFunc_GetCheckedState_ReturnValue;
	Parms.K2Node_ComponentBoundEvent_bIsChecked = K2Node_ComponentBoundEvent_bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Checkbox.WBP_Checkbox_C.BndEvt__CBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Checkbox_C::BndEvt__CBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Checkbox_C", "BndEvt__CBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::WBP_Checkbox_C_BndEvt__CBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Checkbox.WBP_Checkbox_C.GetCheckedState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// enum class ECheckBoxState               CheckedState                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// enum class ECheckBoxState               CallFunc_GetCheckedState_ReturnValue                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Checkbox_C::GetCheckedState(enum class ECheckBoxState* CheckedState, enum class ECheckBoxState CallFunc_GetCheckedState_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Checkbox_C", "GetCheckedState");

	Params::WBP_Checkbox_C_GetCheckedState Parms{};

	Parms.CallFunc_GetCheckedState_ReturnValue = CallFunc_GetCheckedState_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);

	if (CheckedState != nullptr)
		*CheckedState = std::move(Parms.CheckedState);
}


// Function WBP_Checkbox.WBP_Checkbox_C.IsChecked
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    bChecked                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_IsChecked_ReturnValue                         (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Checkbox_C::IsChecked(bool* bChecked, bool CallFunc_IsChecked_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Checkbox_C", "IsChecked");

	Params::WBP_Checkbox_C_IsChecked Parms{};

	Parms.CallFunc_IsChecked_ReturnValue = CallFunc_IsChecked_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);

	if (bChecked != nullptr)
		*bChecked = std::move(Parms.bChecked);
}


// Function WBP_Checkbox.WBP_Checkbox_C.SetIsChecked
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bChecked                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Checkbox_C::SetIsChecked(bool bChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Checkbox_C", "SetIsChecked");

	Params::WBP_Checkbox_C_SetIsChecked Parms{};

	Parms.bChecked = bChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Checkbox.WBP_Checkbox_C.SetCheckedState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// enum class ECheckBoxState               NewCheckedState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Checkbox_C::SetCheckedState(enum class ECheckBoxState NewCheckedState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Checkbox_C", "SetCheckedState");

	Params::WBP_Checkbox_C_SetCheckedState Parms{};

	Parms.NewCheckedState = NewCheckedState;

	UObject::ProcessEvent(Func, &Parms);
}

}

