#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CreditsListEntry

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FGameCreditsEntry_structs.hpp"
#include "UMG_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CreditsListEntry.WBP_CreditsListEntry_C
// 0x0068 (0x0298 - 0x0230)
class UWBP_CreditsListEntry_C final  : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0230(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             EntryBodyText;                                     // 0x0238(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_CreditsListHeader_C*               EntryHeader;                                       // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FFGameCreditsEntry                     Header;                                            // 0x0248(0x0030)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)
	struct FMargin                                HeaderPadding;                                     // 0x0278(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	TArray<struct FFGameCreditsEntry>             BodyEntries;                                       // 0x0288(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_CreditsListEntry(int32 EntryPoint, bool K2Node_Event_IsDesignTime, const class FString& CallFunc_CombineBodyText_BodyCombinedStr, const class FString& CallFunc_ToUpper_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue);
	void PreConstruct(bool IsDesignTime);
	void CombineBodyText(class FString* BodyCombinedStr, const class FString& CombinedStr, const class FString& Temp_string_Variable, const class FString& Temp_string_Variable_1, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool Temp_bool_Variable, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, const struct FFGameCreditsEntry& CallFunc_Array_Get_Item, const class FString& K2Node_Select_Default, int32 CallFunc_Array_Length_ReturnValue_1, const class FString& CallFunc_Conv_TextToString_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue, const class FString& CallFunc_Concat_StrStr_ReturnValue_1);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"WBP_CreditsListEntry_C">();
	}
	static class UWBP_CreditsListEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CreditsListEntry_C>();
	}
};

}

