#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MouseInputCatcherOverlay

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MouseInputCatcherOverlay.WBP_MouseInputCatcherOverlay_C
// 0x0008 (0x0238 - 0x0230)
class UWBP_MouseInputCatcherOverlay_C final  : public UUserWidget
{
public:
	class UWBP_OptionsMenuItem_InputKeySelector_C* TargetIKS;                                         // 0x0230(0x0008)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	struct FEventReply OnMouseButtonDown(const struct FGeometry& MyGeometry, struct FPointerEvent& MouseEvent, const struct FEventReply& CallFunc_Handled_ReturnValue, const struct FKey& CallFunc_PointerEvent_GetEffectingButton_ReturnValue);
	void SelectKey(const struct FKey& Key, const struct FInputChord& K2Node_MakeStruct_InputChord);
	struct FEventReply OnMouseWheel(const struct FGeometry& MyGeometry, struct FPointerEvent& MouseEvent, bool Temp_bool_Variable, float CallFunc_PointerEvent_GetWheelDelta_ReturnValue, const struct FKey& Temp_struct_Variable, bool CallFunc_Greater_FloatFloat_ReturnValue, const struct FKey& Temp_struct_Variable_1, const struct FEventReply& CallFunc_Handled_ReturnValue, const struct FEventReply& CallFunc_ClearUserFocus_ReturnValue, const struct FKey& K2Node_Select_Default);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"WBP_MouseInputCatcherOverlay_C">();
	}
	static class UWBP_MouseInputCatcherOverlay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MouseInputCatcherOverlay_C>();
	}
};

}

