#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DeployMenu_DeployButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_DeployMenu_DeployButton.WBP_DeployMenu_DeployButton_C
// 0x05D8 (0x0808 - 0x0230)
class UWBP_DeployMenu_DeployButton_C final  : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0230(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                DeployBtn;                                         // 0x0238(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             DeployBtnText;                                     // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          bCloseBtnBehavior;                                 // 0x0248(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_198D[0x7];                                     // 0x0249(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   DeployText;                                        // 0x0250(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly)
	class FText                                   CloseMenuText;                                     // 0x0268(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly)
	FMulticastInlineDelegateProperty_             OnClicked;                                         // 0x0280(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnPressed;                                         // 0x0290(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnReleased;                                        // 0x02A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnHovered;                                         // 0x02B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnUnhovered;                                       // 0x02C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class FText                                   SelectSpawnText;                                   // 0x02D0(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly)
	bool                                          bDeploying;                                        // 0x02E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_198E[0x7];                                     // 0x02E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FButtonStyle                           DeployBtnStyle;                                    // 0x02F0(0x0278)(Edit, BlueprintVisible, BlueprintReadOnly)
	struct FButtonStyle                           CancelBtnStyle;                                    // 0x0568(0x0278)(Edit, BlueprintVisible, BlueprintReadOnly)
	bool                                          bDesignPreviewCancelBtn;                           // 0x07E0(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_198F[0x7];                                     // 0x07E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CancelDeploymentText;                              // 0x07E8(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly)
	bool                                          bSpawnPointSelected;                               // 0x0800(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bUseCancelBehavior;                                // 0x0801(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void OnClicked__DelegateSignature(bool bCloseBtn);
	void OnPressed__DelegateSignature(bool bCloseBtn);
	void OnReleased__DelegateSignature(bool bCloseBtn);
	void OnHovered__DelegateSignature(bool bCloseBtn);
	void OnUnhovered__DelegateSignature(bool bCloseBtn);
	void ExecuteUbergraph_WBP_DeployMenu_DeployButton(int32 EntryPoint, bool K2Node_Event_IsDesignTime, bool CallFunc_BooleanAND_ReturnValue, const struct FGeometry& K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class AHDPlayerController* K2Node_DynamicCast_AsHDPlayer_Controller, bool K2Node_DynamicCast_bSuccess, const struct FTimerHandle& CallFunc_GetUnFreezeTimerHandle_ReturnValue, bool CallFunc_K2_IsTimerActiveHandle_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool Temp_bool_Variable, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_2, bool CallFunc_BooleanOR_ReturnValue_1, struct FButtonStyle& K2Node_Select_Default, int32 CallFunc_InternalGetSpawnTimeRemaining_SpawnSeconds, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_InternalGetSpawnTimeRemaining_SpawnSeconds_1, bool CallFunc_Less_IntInt_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue_2);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void BndEvt__DeployBtn_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__DeployBtn_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__DeployBtn_K2Node_ComponentBoundEvent_2_OnButtonReleasedEvent__DelegateSignature();
	void BndEvt__DeployBtn_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature();
	void BndEvt__DeployBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void PreConstruct(bool IsDesignTime);
	void UpdateDeployBtnState(bool bPlayerAlive, bool bDeploymentQueued, bool Param_bSpawnPointSelected, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class AHDPlayerController* K2Node_DynamicCast_AsHDPlayer_Controller, bool K2Node_DynamicCast_bSuccess, const struct FTimerHandle& CallFunc_GetUnFreezeTimerHandle_ReturnValue, bool CallFunc_K2_IsTimerActiveHandle_ReturnValue, int32 CallFunc_InternalGetSpawnTimeRemaining_SpawnSeconds, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue);
	void InternalUpdateBtnText(bool Param_bDeploying, bool Param_bSpawnPointSelected, bool Temp_bool_Variable, bool Temp_bool_Variable_1, bool Temp_bool_Variable_2, bool Temp_bool_Variable_3, int32 CallFunc_InternalGetSpawnTimeRemaining_SpawnSeconds, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, class FText CallFunc_Format_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_2, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array_1, class FText CallFunc_Format_ReturnValue_1, class FText K2Node_Select_Default, class FText K2Node_Select_Default_1, class FText K2Node_Select_Default_2, class FText K2Node_Select_Default_3, class FText CallFunc_TextToUpper_ReturnValue);
	void InternalUpdateBtnStyle(bool Temp_bool_Variable, bool CallFunc_BooleanAND_ReturnValue, struct FButtonStyle& K2Node_Select_Default);
	void InternalGetSpawnTimeRemaining(int32* SpawnSeconds, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class AHDPlayerController* K2Node_DynamicCast_AsHDPlayer_Controller, bool K2Node_DynamicCast_bSuccess, const struct FTimerHandle& CallFunc_GetUnFreezeTimerHandle_ReturnValue, float CallFunc_K2_GetTimerRemainingTimeHandle_ReturnValue, int32 CallFunc_Round_ReturnValue);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"WBP_DeployMenu_DeployButton_C">();
	}
	static class UWBP_DeployMenu_DeployButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_DeployMenu_DeployButton_C>();
	}
};

}

