#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CaptureStatus_FlagIcon

#include "Basic.hpp"

#include "WBP_CaptureStatus_FlagIcon_classes.hpp"
#include "WBP_CaptureStatus_FlagIcon_parameters.hpp"


namespace SDK
{

// Function WBP_CaptureStatus_FlagIcon.WBP_CaptureStatus_FlagIcon_C.ExecuteUbergraph_WBP_CaptureStatus_FlagIcon
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// enum class ESlateVisibility             Temp_byte_Variable                                     (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// enum class ESlateVisibility             Temp_byte_Variable_1                                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_CustomEvent_bActive                             (ZeroConstructor, IsPlainOldData, NoDestructor)
// enum class EHDTeam                      K2Node_CustomEvent_Team                                (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_CustomEvent_bLocked                             (ZeroConstructor, IsPlainOldData, NoDestructor)
// enum class EHDControlPointObjectiveType K2Node_CustomEvent_ObjType                             (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_Event_IsDesignTime                              (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    Temp_bool_Variable                                     (ZeroConstructor, IsPlainOldData, NoDestructor)
// enum class ESlateVisibility             K2Node_Select_Default                                  (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CaptureStatus_FlagIcon_C::ExecuteUbergraph_WBP_CaptureStatus_FlagIcon(int32 EntryPoint, enum class ESlateVisibility Temp_byte_Variable, enum class ESlateVisibility Temp_byte_Variable_1, bool K2Node_CustomEvent_bActive, enum class EHDTeam K2Node_CustomEvent_Team, bool K2Node_CustomEvent_bLocked, enum class EHDControlPointObjectiveType K2Node_CustomEvent_ObjType, bool K2Node_Event_IsDesignTime, bool Temp_bool_Variable, enum class ESlateVisibility K2Node_Select_Default)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CaptureStatus_FlagIcon_C", "ExecuteUbergraph_WBP_CaptureStatus_FlagIcon");

	Params::WBP_CaptureStatus_FlagIcon_C_ExecuteUbergraph_WBP_CaptureStatus_FlagIcon Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.Temp_byte_Variable = Temp_byte_Variable;
	Parms.Temp_byte_Variable_1 = Temp_byte_Variable_1;
	Parms.K2Node_CustomEvent_bActive = K2Node_CustomEvent_bActive;
	Parms.K2Node_CustomEvent_Team = K2Node_CustomEvent_Team;
	Parms.K2Node_CustomEvent_bLocked = K2Node_CustomEvent_bLocked;
	Parms.K2Node_CustomEvent_ObjType = K2Node_CustomEvent_ObjType;
	Parms.K2Node_Event_IsDesignTime = K2Node_Event_IsDesignTime;
	Parms.Temp_bool_Variable = Temp_bool_Variable;
	Parms.K2Node_Select_Default = K2Node_Select_Default;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CaptureStatus_FlagIcon.WBP_CaptureStatus_FlagIcon_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_CaptureStatus_FlagIcon_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CaptureStatus_FlagIcon_C", "PreConstruct");

	Params::WBP_CaptureStatus_FlagIcon_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CaptureStatus_FlagIcon.WBP_CaptureStatus_FlagIcon_C.OnUpdateIcon
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bActive                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// enum class EHDTeam                      Team                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bLocked                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// enum class EHDControlPointObjectiveType ObjType                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CaptureStatus_FlagIcon_C::OnUpdateIcon(bool bActive, enum class EHDTeam Team, bool bLocked, enum class EHDControlPointObjectiveType ObjType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CaptureStatus_FlagIcon_C", "OnUpdateIcon");

	Params::WBP_CaptureStatus_FlagIcon_C_OnUpdateIcon Parms{};

	Parms.bActive = bActive;
	Parms.Team = Team;
	Parms.bLocked = bLocked;
	Parms.ObjType = ObjType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CaptureStatus_FlagIcon.WBP_CaptureStatus_FlagIcon_C.SetBrushes
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSlateBrush                      Param_IconFrame                                        (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FSlateBrush                      Param_Bg                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FSlateBrush                      Param_Icon                                             (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_CaptureStatus_FlagIcon_C::SetBrushes(struct FSlateBrush& Param_IconFrame, struct FSlateBrush& Param_Bg, struct FSlateBrush& Param_Icon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CaptureStatus_FlagIcon_C", "SetBrushes");

	Params::WBP_CaptureStatus_FlagIcon_C_SetBrushes Parms{};

	Parms.Param_IconFrame = std::move(Param_IconFrame);
	Parms.Param_Bg = std::move(Param_Bg);
	Parms.Param_Icon = std::move(Param_Icon);

	UObject::ProcessEvent(Func, &Parms);

	Param_IconFrame = std::move(Parms.Param_IconFrame);
	Param_Bg = std::move(Parms.Param_Bg);
	Param_Icon = std::move(Parms.Param_Icon);
}


// Function WBP_CaptureStatus_FlagIcon.WBP_CaptureStatus_FlagIcon_C.UpdateBrushesByTeam
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bLocked                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// enum class EHDTeam                      Team                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// enum class EHDControlPointObjectiveType ObjType                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bInLocked                                              (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FSlateBrush                      IconToUse                                              (Edit, BlueprintVisible)
// class UTexture2D*                       Temp_object_Variable                                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture2D*                       Temp_object_Variable_1                                 (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture2D*                       Temp_object_Variable_2                                 (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// enum class EHDControlPointObjectiveType Temp_byte_Variable                                     (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture2D*                       K2Node_Select_Default                                  (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CaptureStatus_FlagIcon_C::UpdateBrushesByTeam(bool bLocked, enum class EHDTeam Team, enum class EHDControlPointObjectiveType ObjType, bool bInLocked, const struct FSlateBrush& IconToUse, class UTexture2D* Temp_object_Variable, class UTexture2D* Temp_object_Variable_1, class UTexture2D* Temp_object_Variable_2, enum class EHDControlPointObjectiveType Temp_byte_Variable, class UTexture2D* K2Node_Select_Default)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CaptureStatus_FlagIcon_C", "UpdateBrushesByTeam");

	Params::WBP_CaptureStatus_FlagIcon_C_UpdateBrushesByTeam Parms{};

	Parms.bLocked = bLocked;
	Parms.Team = Team;
	Parms.ObjType = ObjType;
	Parms.bInLocked = bInLocked;
	Parms.IconToUse = std::move(IconToUse);
	Parms.Temp_object_Variable = Temp_object_Variable;
	Parms.Temp_object_Variable_1 = Temp_object_Variable_1;
	Parms.Temp_object_Variable_2 = Temp_object_Variable_2;
	Parms.Temp_byte_Variable = Temp_byte_Variable;
	Parms.K2Node_Select_Default = K2Node_Select_Default;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CaptureStatus_FlagIcon.WBP_CaptureStatus_FlagIcon_C.TintBrushByTeam
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      BrushToTint                                            (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// enum class EHDTeam                      Team                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSlateBrush                      NewBrush                                               (Parm, OutParm)
// struct FSlateColor                      TintColor                                              (Edit, BlueprintVisible)
// enum class EHDTeam                      Temp_byte_Variable                                     (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSlateBrush                      K2Node_MakeStruct_SlateBrush                           ()
// struct FSlateColor                      K2Node_Select_Default                                  ()

void UWBP_CaptureStatus_FlagIcon_C::TintBrushByTeam(struct FSlateBrush& BrushToTint, enum class EHDTeam Team, struct FSlateBrush* NewBrush, const struct FSlateColor& TintColor, enum class EHDTeam Temp_byte_Variable, const struct FSlateBrush& K2Node_MakeStruct_SlateBrush, const struct FSlateColor& K2Node_Select_Default)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CaptureStatus_FlagIcon_C", "TintBrushByTeam");

	Params::WBP_CaptureStatus_FlagIcon_C_TintBrushByTeam Parms{};

	Parms.BrushToTint = std::move(BrushToTint);
	Parms.Team = Team;
	Parms.TintColor = std::move(TintColor);
	Parms.Temp_byte_Variable = Temp_byte_Variable;
	Parms.K2Node_MakeStruct_SlateBrush = std::move(K2Node_MakeStruct_SlateBrush);
	Parms.K2Node_Select_Default = std::move(K2Node_Select_Default);

	UObject::ProcessEvent(Func, &Parms);

	BrushToTint = std::move(Parms.BrushToTint);

	if (NewBrush != nullptr)
		*NewBrush = Parms.NewBrush;
}


// Function WBP_CaptureStatus_FlagIcon.WBP_CaptureStatus_FlagIcon_C.SetBrushOpacityByCaptureStatus
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      BrushToUpdate                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    bLocked                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// enum class EHDControlPointObjectiveType ObjType                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSlateBrush                      NewBrush                                               (Parm, OutParm)
// float                                   OpacityToUse                                           (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Temp_bool_Variable                                     (ZeroConstructor, IsPlainOldData, NoDestructor)
// enum class EHDControlPointObjectiveType Temp_byte_Variable                                     (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     K2Node_MakeStruct_LinearColor                          (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSlateColor                      K2Node_MakeStruct_SlateColor                           ()
// struct FSlateBrush                      K2Node_MakeStruct_SlateBrush                           ()
// float                                   K2Node_Select_Default                                  (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   K2Node_Select_Default_1                                (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CaptureStatus_FlagIcon_C::SetBrushOpacityByCaptureStatus(struct FSlateBrush& BrushToUpdate, bool bLocked, enum class EHDControlPointObjectiveType ObjType, struct FSlateBrush* NewBrush, float OpacityToUse, bool Temp_bool_Variable, enum class EHDControlPointObjectiveType Temp_byte_Variable, const struct FLinearColor& K2Node_MakeStruct_LinearColor, const struct FSlateColor& K2Node_MakeStruct_SlateColor, const struct FSlateBrush& K2Node_MakeStruct_SlateBrush, float K2Node_Select_Default, float K2Node_Select_Default_1)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CaptureStatus_FlagIcon_C", "SetBrushOpacityByCaptureStatus");

	Params::WBP_CaptureStatus_FlagIcon_C_SetBrushOpacityByCaptureStatus Parms{};

	Parms.BrushToUpdate = std::move(BrushToUpdate);
	Parms.bLocked = bLocked;
	Parms.ObjType = ObjType;
	Parms.OpacityToUse = OpacityToUse;
	Parms.Temp_bool_Variable = Temp_bool_Variable;
	Parms.Temp_byte_Variable = Temp_byte_Variable;
	Parms.K2Node_MakeStruct_LinearColor = std::move(K2Node_MakeStruct_LinearColor);
	Parms.K2Node_MakeStruct_SlateColor = std::move(K2Node_MakeStruct_SlateColor);
	Parms.K2Node_MakeStruct_SlateBrush = std::move(K2Node_MakeStruct_SlateBrush);
	Parms.K2Node_Select_Default = K2Node_Select_Default;
	Parms.K2Node_Select_Default_1 = K2Node_Select_Default_1;

	UObject::ProcessEvent(Func, &Parms);

	BrushToUpdate = std::move(Parms.BrushToUpdate);

	if (NewBrush != nullptr)
		*NewBrush = Parms.NewBrush;
}

}

