#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EntitlementBadge

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_EntitlementBadge.WBP_EntitlementBadge_C.ExecuteUbergraph_WBP_EntitlementBadge
// 0x0005 (0x0005 - 0x0000)
struct WBP_EntitlementBadge_C_ExecuteUbergraph_WBP_EntitlementBadge final 
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function WBP_EntitlementBadge.WBP_EntitlementBadge_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_EntitlementBadge_C_PreConstruct final  : public UserWidget_PreConstruct
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

}

