#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DeployMenu_SquadList

#include "Basic.hpp"

#include "WBP_DeployMenu_SquadList_classes.hpp"
#include "WBP_DeployMenu_SquadList_parameters.hpp"


namespace SDK
{

// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.ExecuteUbergraph_WBP_DeployMenu_SquadList
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USquadMemberInfo*                 K2Node_Event_MemberData                                (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USquadMemberInfo*                 K2Node_Event_RemovedMemberData                         (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_Not_PreBool_ReturnValue                       (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_WasListCollapsedByUser_bCollapsedByUser       (ZeroConstructor, IsPlainOldData, NoDestructor)
// class APlayerController*                CallFunc_GetOwningPlayer_ReturnValue                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_Not_PreBool_ReturnValue_1                     (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_EqualEqual_ObjectObject_ReturnValue           (ZeroConstructor, IsPlainOldData, NoDestructor)
// class APlayerController*                CallFunc_GetOwningPlayer_ReturnValue_1                 (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_BooleanAND_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor)
// class ABP_HDPlayerControllerBase_C*     K2Node_DynamicCast_AsBP_HDPlayer_Controller_Base       (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess                            (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_BooleanOR_ReturnValue                         (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_LeaveCurrentSquad_bLeaveSuccess               (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_IsOwningPlayerRegisteredSquadMember_bRegisteredMember(ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_IsSquadValid_bValidSQ                         (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_IsSquadValid_bValidSQ_1                       (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_Not_PreBool_ReturnValue_2                     (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    K2Node_Event_IsDesignTime                              (ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   CallFunc_Subtract_IntInt_ReturnValue                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             K2Node_Event_NewSquadName                              (ConstParm)
// class FText                             K2Node_Event_PreviousSquadName                         (ConstParm)
// bool                                    CallFunc_BooleanAND_ReturnValue_1                      (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_BooleanOR_ReturnValue_1                       (ZeroConstructor, IsPlainOldData, NoDestructor)
// class AHDPlayerState*                   K2Node_Event_NewLeaderPS                               (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AHDPlayerState*                   K2Node_Event_PrevLeaderPS                              (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_Event_bNewLockedState                           (ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   Temp_int_Variable                                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_LessEqual_IntInt_ReturnValue                  (ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   CallFunc_Add_IntInt_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_JoinSquad_bJoinSuccess                        (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::ExecuteUbergraph_WBP_DeployMenu_SquadList(int32 EntryPoint, class USquadMemberInfo* K2Node_Event_MemberData, class USquadMemberInfo* K2Node_Event_RemovedMemberData, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_WasListCollapsedByUser_bCollapsedByUser, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, class ABP_HDPlayerControllerBase_C* K2Node_DynamicCast_AsBP_HDPlayer_Controller_Base, bool K2Node_DynamicCast_bSuccess, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_LeaveCurrentSquad_bLeaveSuccess, bool CallFunc_IsOwningPlayerRegisteredSquadMember_bRegisteredMember, bool CallFunc_IsSquadValid_bValidSQ, bool CallFunc_IsSquadValid_bValidSQ_1, bool CallFunc_Not_PreBool_ReturnValue_2, bool K2Node_Event_IsDesignTime, int32 CallFunc_Subtract_IntInt_ReturnValue, class FText K2Node_Event_NewSquadName, class FText K2Node_Event_PreviousSquadName, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue_1, class AHDPlayerState* K2Node_Event_NewLeaderPS, class AHDPlayerState* K2Node_Event_PrevLeaderPS, bool K2Node_Event_bNewLockedState, int32 Temp_int_Variable, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_JoinSquad_bJoinSuccess)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "ExecuteUbergraph_WBP_DeployMenu_SquadList");

	Params::WBP_DeployMenu_SquadList_C_ExecuteUbergraph_WBP_DeployMenu_SquadList Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.K2Node_Event_MemberData = K2Node_Event_MemberData;
	Parms.K2Node_Event_RemovedMemberData = K2Node_Event_RemovedMemberData;
	Parms.CallFunc_Not_PreBool_ReturnValue = CallFunc_Not_PreBool_ReturnValue;
	Parms.CallFunc_WasListCollapsedByUser_bCollapsedByUser = CallFunc_WasListCollapsedByUser_bCollapsedByUser;
	Parms.CallFunc_GetOwningPlayer_ReturnValue = CallFunc_GetOwningPlayer_ReturnValue;
	Parms.CallFunc_Not_PreBool_ReturnValue_1 = CallFunc_Not_PreBool_ReturnValue_1;
	Parms.CallFunc_EqualEqual_ObjectObject_ReturnValue = CallFunc_EqualEqual_ObjectObject_ReturnValue;
	Parms.CallFunc_GetOwningPlayer_ReturnValue_1 = CallFunc_GetOwningPlayer_ReturnValue_1;
	Parms.CallFunc_BooleanAND_ReturnValue = CallFunc_BooleanAND_ReturnValue;
	Parms.K2Node_DynamicCast_AsBP_HDPlayer_Controller_Base = K2Node_DynamicCast_AsBP_HDPlayer_Controller_Base;
	Parms.K2Node_DynamicCast_bSuccess = K2Node_DynamicCast_bSuccess;
	Parms.CallFunc_BooleanOR_ReturnValue = CallFunc_BooleanOR_ReturnValue;
	Parms.CallFunc_LeaveCurrentSquad_bLeaveSuccess = CallFunc_LeaveCurrentSquad_bLeaveSuccess;
	Parms.CallFunc_IsOwningPlayerRegisteredSquadMember_bRegisteredMember = CallFunc_IsOwningPlayerRegisteredSquadMember_bRegisteredMember;
	Parms.CallFunc_IsSquadValid_bValidSQ = CallFunc_IsSquadValid_bValidSQ;
	Parms.CallFunc_IsSquadValid_bValidSQ_1 = CallFunc_IsSquadValid_bValidSQ_1;
	Parms.CallFunc_Not_PreBool_ReturnValue_2 = CallFunc_Not_PreBool_ReturnValue_2;
	Parms.K2Node_Event_IsDesignTime = K2Node_Event_IsDesignTime;
	Parms.CallFunc_Subtract_IntInt_ReturnValue = CallFunc_Subtract_IntInt_ReturnValue;
	Parms.K2Node_Event_NewSquadName = K2Node_Event_NewSquadName;
	Parms.K2Node_Event_PreviousSquadName = K2Node_Event_PreviousSquadName;
	Parms.CallFunc_BooleanAND_ReturnValue_1 = CallFunc_BooleanAND_ReturnValue_1;
	Parms.CallFunc_BooleanOR_ReturnValue_1 = CallFunc_BooleanOR_ReturnValue_1;
	Parms.K2Node_Event_NewLeaderPS = K2Node_Event_NewLeaderPS;
	Parms.K2Node_Event_PrevLeaderPS = K2Node_Event_PrevLeaderPS;
	Parms.K2Node_Event_bNewLockedState = K2Node_Event_bNewLockedState;
	Parms.Temp_int_Variable = Temp_int_Variable;
	Parms.CallFunc_LessEqual_IntInt_ReturnValue = CallFunc_LessEqual_IntInt_ReturnValue;
	Parms.CallFunc_Add_IntInt_ReturnValue = CallFunc_Add_IntInt_ReturnValue;
	Parms.CallFunc_JoinSquad_bJoinSuccess = CallFunc_JoinSquad_bJoinSuccess;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.OnSquadLockStateUpdated
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bNewLockedState                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::OnSquadLockStateUpdated(bool bNewLockedState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "OnSquadLockStateUpdated");

	Params::WBP_DeployMenu_SquadList_C_OnSquadLockStateUpdated Parms{};

	Parms.bNewLockedState = bNewLockedState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.OnSquadLeaderUpdated
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AHDPlayerState*                   NewLeaderPS                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AHDPlayerState*                   PrevLeaderPS                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DeployMenu_SquadList_C::OnSquadLeaderUpdated(class AHDPlayerState* NewLeaderPS, class AHDPlayerState* PrevLeaderPS)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "OnSquadLeaderUpdated");

	Params::WBP_DeployMenu_SquadList_C_OnSquadLeaderUpdated Parms{};

	Parms.NewLeaderPS = NewLeaderPS;
	Parms.PrevLeaderPS = PrevLeaderPS;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.OnSquadNameUpdated
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             NewSquadName                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FText                             PreviousSquadName                                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_DeployMenu_SquadList_C::OnSquadNameUpdated(class FText& NewSquadName, class FText& PreviousSquadName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "OnSquadNameUpdated");

	Params::WBP_DeployMenu_SquadList_C_OnSquadNameUpdated Parms{};

	Parms.NewSquadName = NewSquadName;
	Parms.PreviousSquadName = PreviousSquadName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.OnSquadSet
// (Event, Protected, BlueprintEvent)

void UWBP_DeployMenu_SquadList_C::OnSquadSet()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "OnSquadSet");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.SquadMembersListCollapsed
// (BlueprintCallable, BlueprintEvent)

void UWBP_DeployMenu_SquadList_C::SquadMembersListCollapsed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "SquadMembersListCollapsed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.SquadMembersListExpanded
// (BlueprintCallable, BlueprintEvent)

void UWBP_DeployMenu_SquadList_C::SquadMembersListExpanded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "SquadMembersListExpanded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "PreConstruct");

	Params::WBP_DeployMenu_SquadList_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.BndEvt__ExpandBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_DeployMenu_SquadList_C::BndEvt__ExpandBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "BndEvt__ExpandBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.BndEvt__LeaveSquadBtn_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_DeployMenu_SquadList_C::BndEvt__LeaveSquadBtn_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "BndEvt__LeaveSquadBtn_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.DeconstructSquadMember
// (Event, Protected, BlueprintEvent)
// Parameters:
// class USquadMemberInfo*                 RemovedMemberData                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DeployMenu_SquadList_C::DeconstructSquadMember(class USquadMemberInfo* RemovedMemberData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "DeconstructSquadMember");

	Params::WBP_DeployMenu_SquadList_C_DeconstructSquadMember Parms{};

	Parms.RemovedMemberData = RemovedMemberData;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.GenerateSquadMember
// (Event, Protected, BlueprintEvent)
// Parameters:
// class USquadMemberInfo*                 MemberData                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DeployMenu_SquadList_C::GenerateSquadMember(class USquadMemberInfo* MemberData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "GenerateSquadMember");

	Params::WBP_DeployMenu_SquadList_C_GenerateSquadMember Parms{};

	Parms.MemberData = MemberData;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.BndEvt__LockUnlockSQOptionBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_DeployMenu_SquadList_C::BndEvt__LockUnlockSQOptionBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "BndEvt__LockUnlockSQOptionBtn_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.ExpandList
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bExpandParent                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_HasAnySquadMembers_bValidMembersPresent       (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_Not_PreBool_ReturnValue                       (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_BooleanAND_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::ExpandList(bool bExpandParent, bool CallFunc_HasAnySquadMembers_bValidMembersPresent, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "ExpandList");

	Params::WBP_DeployMenu_SquadList_C_ExpandList Parms{};

	Parms.bExpandParent = bExpandParent;
	Parms.CallFunc_HasAnySquadMembers_bValidMembersPresent = CallFunc_HasAnySquadMembers_bValidMembersPresent;
	Parms.CallFunc_Not_PreBool_ReturnValue = CallFunc_Not_PreBool_ReturnValue;
	Parms.CallFunc_BooleanAND_ReturnValue = CallFunc_BooleanAND_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.CollapseList
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bCollapseParent                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::CollapseList(bool bCollapseParent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "CollapseList");

	Params::WBP_DeployMenu_SquadList_C_CollapseList Parms{};

	Parms.bCollapseParent = bCollapseParent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.AddNewSquadMemberItemWidget
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USquadMemberInfo*                 MemberData                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWBP_DeployMenu_SquadMemberListing_C*CallFunc_Create_ReturnValue                            (ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_GetChildrenCount_ReturnValue                  (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Add_IntInt_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Percent_IntInt_ReturnValue                    (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UVerticalBoxSlot*                 CallFunc_AddChildToVerticalBox_ReturnValue             (ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_EqualEqual_IntInt_ReturnValue                 (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_IsValid_ReturnValue                           (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::AddNewSquadMemberItemWidget(class USquadMemberInfo* MemberData, class UWBP_DeployMenu_SquadMemberListing_C* CallFunc_Create_ReturnValue, int32 CallFunc_GetChildrenCount_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Percent_IntInt_ReturnValue, class UVerticalBoxSlot* CallFunc_AddChildToVerticalBox_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "AddNewSquadMemberItemWidget");

	Params::WBP_DeployMenu_SquadList_C_AddNewSquadMemberItemWidget Parms{};

	Parms.MemberData = MemberData;
	Parms.CallFunc_Create_ReturnValue = CallFunc_Create_ReturnValue;
	Parms.CallFunc_GetChildrenCount_ReturnValue = CallFunc_GetChildrenCount_ReturnValue;
	Parms.CallFunc_Add_IntInt_ReturnValue = CallFunc_Add_IntInt_ReturnValue;
	Parms.CallFunc_Percent_IntInt_ReturnValue = CallFunc_Percent_IntInt_ReturnValue;
	Parms.CallFunc_AddChildToVerticalBox_ReturnValue = CallFunc_AddChildToVerticalBox_ReturnValue;
	Parms.CallFunc_EqualEqual_IntInt_ReturnValue = CallFunc_EqualEqual_IntInt_ReturnValue;
	Parms.CallFunc_IsValid_ReturnValue = CallFunc_IsValid_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.RemoveSquadMemberItemWidgetFromList
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USquadMemberInfo*                 RemovedMemberData                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Temp_int_Array_Index_Variable                          (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Temp_int_Loop_Counter_Variable                         (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Add_IntInt_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Temp_int_Array_Index_Variable_1                        (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Add_IntInt_ReturnValue_1                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Percent_IntInt_ReturnValue                    (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_EqualEqual_IntInt_ReturnValue                 (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_RemoveChildAt_ReturnValue                     (ZeroConstructor, IsPlainOldData, NoDestructor)
// TArray<class UWidget*>                  CallFunc_GetAllChildren_ReturnValue                    (ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)
// class UWidget*                          CallFunc_Array_Get_Item                                (ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Array_Length_ReturnValue                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWBP_DeployMenu_SquadMemberListing_C*K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess                            (ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   Temp_int_Loop_Counter_Variable_1                       (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_EqualEqual_ObjectObject_ReturnValue           (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_EqualEqual_ObjectObject_ReturnValue_1         (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_Less_IntInt_ReturnValue                       (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_BooleanOR_ReturnValue                         (ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   CallFunc_Add_IntInt_ReturnValue_2                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class UWidget*>                  CallFunc_GetAllChildren_ReturnValue_1                  (ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)
// int32                                   CallFunc_Array_Length_ReturnValue_1                    (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          CallFunc_Array_Get_Item_1                              (ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_Less_IntInt_ReturnValue_1                     (ZeroConstructor, IsPlainOldData, NoDestructor)
// class UWBP_DeployMenu_SquadMemberListing_C*K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing_1(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess_1                          (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::RemoveSquadMemberItemWidgetFromList(class USquadMemberInfo* RemovedMemberData, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_Percent_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_RemoveChildAt_ReturnValue, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, class UWidget* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class UWBP_DeployMenu_SquadMemberListing_C* K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing, bool K2Node_DynamicCast_bSuccess, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_2, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_1, class UWidget* CallFunc_Array_Get_Item_1, bool CallFunc_Less_IntInt_ReturnValue_1, class UWBP_DeployMenu_SquadMemberListing_C* K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing_1, bool K2Node_DynamicCast_bSuccess_1)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "RemoveSquadMemberItemWidgetFromList");

	Params::WBP_DeployMenu_SquadList_C_RemoveSquadMemberItemWidgetFromList Parms{};

	Parms.RemovedMemberData = RemovedMemberData;
	Parms.Temp_int_Array_Index_Variable = Temp_int_Array_Index_Variable;
	Parms.Temp_int_Loop_Counter_Variable = Temp_int_Loop_Counter_Variable;
	Parms.CallFunc_Add_IntInt_ReturnValue = CallFunc_Add_IntInt_ReturnValue;
	Parms.Temp_int_Array_Index_Variable_1 = Temp_int_Array_Index_Variable_1;
	Parms.CallFunc_Add_IntInt_ReturnValue_1 = CallFunc_Add_IntInt_ReturnValue_1;
	Parms.CallFunc_Percent_IntInt_ReturnValue = CallFunc_Percent_IntInt_ReturnValue;
	Parms.CallFunc_EqualEqual_IntInt_ReturnValue = CallFunc_EqualEqual_IntInt_ReturnValue;
	Parms.CallFunc_RemoveChildAt_ReturnValue = CallFunc_RemoveChildAt_ReturnValue;
	Parms.CallFunc_GetAllChildren_ReturnValue = std::move(CallFunc_GetAllChildren_ReturnValue);
	Parms.CallFunc_Array_Get_Item = CallFunc_Array_Get_Item;
	Parms.CallFunc_Array_Length_ReturnValue = CallFunc_Array_Length_ReturnValue;
	Parms.K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing = K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing;
	Parms.K2Node_DynamicCast_bSuccess = K2Node_DynamicCast_bSuccess;
	Parms.Temp_int_Loop_Counter_Variable_1 = Temp_int_Loop_Counter_Variable_1;
	Parms.CallFunc_EqualEqual_ObjectObject_ReturnValue = CallFunc_EqualEqual_ObjectObject_ReturnValue;
	Parms.CallFunc_EqualEqual_ObjectObject_ReturnValue_1 = CallFunc_EqualEqual_ObjectObject_ReturnValue_1;
	Parms.CallFunc_Less_IntInt_ReturnValue = CallFunc_Less_IntInt_ReturnValue;
	Parms.CallFunc_BooleanOR_ReturnValue = CallFunc_BooleanOR_ReturnValue;
	Parms.CallFunc_Add_IntInt_ReturnValue_2 = CallFunc_Add_IntInt_ReturnValue_2;
	Parms.CallFunc_GetAllChildren_ReturnValue_1 = std::move(CallFunc_GetAllChildren_ReturnValue_1);
	Parms.CallFunc_Array_Length_ReturnValue_1 = CallFunc_Array_Length_ReturnValue_1;
	Parms.CallFunc_Array_Get_Item_1 = CallFunc_Array_Get_Item_1;
	Parms.CallFunc_Less_IntInt_ReturnValue_1 = CallFunc_Less_IntInt_ReturnValue_1;
	Parms.K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing_1 = K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing_1;
	Parms.K2Node_DynamicCast_bSuccess_1 = K2Node_DynamicCast_bSuccess_1;

	UObject::ProcessEvent(Func, &Parms);

	CallFunc_GetAllChildren_ReturnValue = std::move(Parms.CallFunc_GetAllChildren_ReturnValue);
	CallFunc_GetAllChildren_ReturnValue_1 = std::move(Parms.CallFunc_GetAllChildren_ReturnValue_1);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.SetSquadNameText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             NewSquadName                                           (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             CallFunc_TextToUpper_ReturnValue                       ()
// struct FFormatArgumentData              K2Node_MakeStruct_FormatArgumentData                   (HasGetValueTypeHash)
// TArray<struct FFormatArgumentData>      K2Node_MakeArray_Array                                 (ReferenceParm, HasGetValueTypeHash)
// class FText                             CallFunc_Format_ReturnValue                            ()

void UWBP_DeployMenu_SquadList_C::SetSquadNameText(class FText NewSquadName, class FText CallFunc_TextToUpper_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "SetSquadNameText");

	Params::WBP_DeployMenu_SquadList_C_SetSquadNameText Parms{};

	Parms.NewSquadName = NewSquadName;
	Parms.CallFunc_TextToUpper_ReturnValue = CallFunc_TextToUpper_ReturnValue;
	Parms.K2Node_MakeStruct_FormatArgumentData = std::move(K2Node_MakeStruct_FormatArgumentData);
	Parms.K2Node_MakeArray_Array = std::move(K2Node_MakeArray_Array);
	Parms.CallFunc_Format_ReturnValue = CallFunc_Format_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);

	K2Node_MakeArray_Array = std::move(Parms.K2Node_MakeArray_Array);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.CollapseListIfEmpty
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bCollapseParentIfEmpty                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_HasAnySquadMembers_bValidMembersPresent       (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::CollapseListIfEmpty(bool bCollapseParentIfEmpty, bool CallFunc_HasAnySquadMembers_bValidMembersPresent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "CollapseListIfEmpty");

	Params::WBP_DeployMenu_SquadList_C_CollapseListIfEmpty Parms{};

	Parms.bCollapseParentIfEmpty = bCollapseParentIfEmpty;
	Parms.CallFunc_HasAnySquadMembers_bValidMembersPresent = CallFunc_HasAnySquadMembers_bValidMembersPresent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.UpdateSquadMemberCountText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   CallFunc_GetNumSquadMembers_ReturnValue                (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FFormatArgumentData              K2Node_MakeStruct_FormatArgumentData                   (HasGetValueTypeHash)
// struct FFormatArgumentData              K2Node_MakeStruct_FormatArgumentData_1                 (HasGetValueTypeHash)
// TArray<struct FFormatArgumentData>      K2Node_MakeArray_Array                                 (ReferenceParm, HasGetValueTypeHash)
// class FText                             CallFunc_Format_ReturnValue                            ()

void UWBP_DeployMenu_SquadList_C::UpdateSquadMemberCountText(int32 CallFunc_GetNumSquadMembers_ReturnValue, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData_1, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, class FText CallFunc_Format_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "UpdateSquadMemberCountText");

	Params::WBP_DeployMenu_SquadList_C_UpdateSquadMemberCountText Parms{};

	Parms.CallFunc_GetNumSquadMembers_ReturnValue = CallFunc_GetNumSquadMembers_ReturnValue;
	Parms.K2Node_MakeStruct_FormatArgumentData = std::move(K2Node_MakeStruct_FormatArgumentData);
	Parms.K2Node_MakeStruct_FormatArgumentData_1 = std::move(K2Node_MakeStruct_FormatArgumentData_1);
	Parms.K2Node_MakeArray_Array = std::move(K2Node_MakeArray_Array);
	Parms.CallFunc_Format_ReturnValue = CallFunc_Format_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);

	K2Node_MakeArray_Array = std::move(Parms.K2Node_MakeArray_Array);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.UpdateJoinLeaveBtnState
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Temp_bool_Variable                                     (ZeroConstructor, IsPlainOldData, NoDestructor)
// class FText                             Temp_text_Variable                                     ()
// class FText                             Temp_text_Variable_1                                   ()
// bool                                    CallFunc_IsOwningPlayerRegisteredSquadMember_bRegisteredMember(ZeroConstructor, IsPlainOldData, NoDestructor)
// class FText                             K2Node_Select_Default                                  ()
// bool                                    CallFunc_Not_PreBool_ReturnValue                       (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_HasReachedMaxSquadMemberLimit_ReturnValue     (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_Not_PreBool_ReturnValue_1                     (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_BooleanAND_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_BooleanOR_ReturnValue                         (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::UpdateJoinLeaveBtnState(bool Temp_bool_Variable, class FText Temp_text_Variable, class FText Temp_text_Variable_1, bool CallFunc_IsOwningPlayerRegisteredSquadMember_bRegisteredMember, class FText K2Node_Select_Default, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_HasReachedMaxSquadMemberLimit_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_BooleanOR_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "UpdateJoinLeaveBtnState");

	Params::WBP_DeployMenu_SquadList_C_UpdateJoinLeaveBtnState Parms{};

	Parms.Temp_bool_Variable = Temp_bool_Variable;
	Parms.Temp_text_Variable = Temp_text_Variable;
	Parms.Temp_text_Variable_1 = Temp_text_Variable_1;
	Parms.CallFunc_IsOwningPlayerRegisteredSquadMember_bRegisteredMember = CallFunc_IsOwningPlayerRegisteredSquadMember_bRegisteredMember;
	Parms.K2Node_Select_Default = K2Node_Select_Default;
	Parms.CallFunc_Not_PreBool_ReturnValue = CallFunc_Not_PreBool_ReturnValue;
	Parms.CallFunc_HasReachedMaxSquadMemberLimit_ReturnValue = CallFunc_HasReachedMaxSquadMemberLimit_ReturnValue;
	Parms.CallFunc_Not_PreBool_ReturnValue_1 = CallFunc_Not_PreBool_ReturnValue_1;
	Parms.CallFunc_BooleanAND_ReturnValue = CallFunc_BooleanAND_ReturnValue;
	Parms.CallFunc_BooleanOR_ReturnValue = CallFunc_BooleanOR_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.IsOwningPlayerRegisteredSquadMember
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    bIgnorePendingRemoval                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bRegisteredMember                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class APlayerController*                CallFunc_GetOwningPlayer_ReturnValue                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AHDPlayerController*              K2Node_DynamicCast_AsHDPlayer_Controller               (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess                            (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_IsPlayerRegisteredSquadMember_ReturnValue     (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::IsOwningPlayerRegisteredSquadMember(bool bIgnorePendingRemoval, bool* bRegisteredMember, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class AHDPlayerController* K2Node_DynamicCast_AsHDPlayer_Controller, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsPlayerRegisteredSquadMember_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "IsOwningPlayerRegisteredSquadMember");

	Params::WBP_DeployMenu_SquadList_C_IsOwningPlayerRegisteredSquadMember Parms{};

	Parms.bIgnorePendingRemoval = bIgnorePendingRemoval;
	Parms.CallFunc_GetOwningPlayer_ReturnValue = CallFunc_GetOwningPlayer_ReturnValue;
	Parms.K2Node_DynamicCast_AsHDPlayer_Controller = K2Node_DynamicCast_AsHDPlayer_Controller;
	Parms.K2Node_DynamicCast_bSuccess = K2Node_DynamicCast_bSuccess;
	Parms.CallFunc_IsPlayerRegisteredSquadMember_ReturnValue = CallFunc_IsPlayerRegisteredSquadMember_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);

	if (bRegisteredMember != nullptr)
		*bRegisteredMember = std::move(Parms.bRegisteredMember);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.IsOwningPlayerRegisteredSquadLeader
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    bSquadLeader                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class APlayerController*                CallFunc_GetOwningPlayer_ReturnValue                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AHDPlayerController*              K2Node_DynamicCast_AsHDPlayer_Controller               (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess                            (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_IsPlayerRegisteredSquadMember_ReturnValue     (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_EqualEqual_ObjectObject_ReturnValue           (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_BooleanAND_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::IsOwningPlayerRegisteredSquadLeader(bool* bSquadLeader, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class AHDPlayerController* K2Node_DynamicCast_AsHDPlayer_Controller, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsPlayerRegisteredSquadMember_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_BooleanAND_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "IsOwningPlayerRegisteredSquadLeader");

	Params::WBP_DeployMenu_SquadList_C_IsOwningPlayerRegisteredSquadLeader Parms{};

	Parms.CallFunc_GetOwningPlayer_ReturnValue = CallFunc_GetOwningPlayer_ReturnValue;
	Parms.K2Node_DynamicCast_AsHDPlayer_Controller = K2Node_DynamicCast_AsHDPlayer_Controller;
	Parms.K2Node_DynamicCast_bSuccess = K2Node_DynamicCast_bSuccess;
	Parms.CallFunc_IsPlayerRegisteredSquadMember_ReturnValue = CallFunc_IsPlayerRegisteredSquadMember_ReturnValue;
	Parms.CallFunc_EqualEqual_ObjectObject_ReturnValue = CallFunc_EqualEqual_ObjectObject_ReturnValue;
	Parms.CallFunc_BooleanAND_ReturnValue = CallFunc_BooleanAND_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);

	if (bSquadLeader != nullptr)
		*bSquadLeader = std::move(Parms.bSquadLeader);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.TestSQPrereqs
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Temp_int_Array_Index_Variable                          (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Temp_int_Loop_Counter_Variable                         (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Add_IntInt_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class UWidget*>                  CallFunc_GetAllChildren_ReturnValue                    (ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)
// int32                                   CallFunc_Array_Length_ReturnValue                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          CallFunc_Array_Get_Item                                (ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_Less_IntInt_ReturnValue                       (ZeroConstructor, IsPlainOldData, NoDestructor)
// class UDFContextualWidgetBase*          K2Node_DynamicCast_AsDFContextual_Widget_Base          (ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess                            (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_TestPrerequisites_ReturnValue                 (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::TestSQPrereqs(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UWidget* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class UDFContextualWidgetBase* K2Node_DynamicCast_AsDFContextual_Widget_Base, bool K2Node_DynamicCast_bSuccess, bool CallFunc_TestPrerequisites_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "TestSQPrereqs");

	Params::WBP_DeployMenu_SquadList_C_TestSQPrereqs Parms{};

	Parms.Temp_int_Array_Index_Variable = Temp_int_Array_Index_Variable;
	Parms.Temp_int_Loop_Counter_Variable = Temp_int_Loop_Counter_Variable;
	Parms.CallFunc_Add_IntInt_ReturnValue = CallFunc_Add_IntInt_ReturnValue;
	Parms.CallFunc_GetAllChildren_ReturnValue = std::move(CallFunc_GetAllChildren_ReturnValue);
	Parms.CallFunc_Array_Length_ReturnValue = CallFunc_Array_Length_ReturnValue;
	Parms.CallFunc_Array_Get_Item = CallFunc_Array_Get_Item;
	Parms.CallFunc_Less_IntInt_ReturnValue = CallFunc_Less_IntInt_ReturnValue;
	Parms.K2Node_DynamicCast_AsDFContextual_Widget_Base = K2Node_DynamicCast_AsDFContextual_Widget_Base;
	Parms.K2Node_DynamicCast_bSuccess = K2Node_DynamicCast_bSuccess;
	Parms.CallFunc_TestPrerequisites_ReturnValue = CallFunc_TestPrerequisites_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);

	CallFunc_GetAllChildren_ReturnValue = std::move(Parms.CallFunc_GetAllChildren_ReturnValue);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.TestSquadAndMemberPrereqs
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_DeployMenu_SquadList_C::TestSquadAndMemberPrereqs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "TestSquadAndMemberPrereqs");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.TestPrereqsForAllMembers
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Temp_int_Array_Index_Variable                          (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Temp_int_Loop_Counter_Variable                         (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Add_IntInt_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class UWidget*>                  CallFunc_GetAllChildren_ReturnValue                    (ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)
// int32                                   CallFunc_Array_Length_ReturnValue                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          CallFunc_Array_Get_Item                                (ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_Less_IntInt_ReturnValue                       (ZeroConstructor, IsPlainOldData, NoDestructor)
// class UWBP_DeployMenu_SquadMemberListing_C*K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess                            (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::TestPrereqsForAllMembers(int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UWidget* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class UWBP_DeployMenu_SquadMemberListing_C* K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing, bool K2Node_DynamicCast_bSuccess)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "TestPrereqsForAllMembers");

	Params::WBP_DeployMenu_SquadList_C_TestPrereqsForAllMembers Parms{};

	Parms.Temp_int_Array_Index_Variable = Temp_int_Array_Index_Variable;
	Parms.Temp_int_Loop_Counter_Variable = Temp_int_Loop_Counter_Variable;
	Parms.CallFunc_Add_IntInt_ReturnValue = CallFunc_Add_IntInt_ReturnValue;
	Parms.CallFunc_GetAllChildren_ReturnValue = std::move(CallFunc_GetAllChildren_ReturnValue);
	Parms.CallFunc_Array_Length_ReturnValue = CallFunc_Array_Length_ReturnValue;
	Parms.CallFunc_Array_Get_Item = CallFunc_Array_Get_Item;
	Parms.CallFunc_Less_IntInt_ReturnValue = CallFunc_Less_IntInt_ReturnValue;
	Parms.K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing = K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing;
	Parms.K2Node_DynamicCast_bSuccess = K2Node_DynamicCast_bSuccess;

	UObject::ProcessEvent(Func, &Parms);

	CallFunc_GetAllChildren_ReturnValue = std::move(Parms.CallFunc_GetAllChildren_ReturnValue);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.IsOwningPlayerInMemberWidgetList
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    bOwnsMemberWidget                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    Temp_bool_True_if_break_was_hit_Variable               (ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   Temp_int_Array_Index_Variable                          (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_Not_PreBool_ReturnValue                       (ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   Temp_int_Loop_Counter_Variable                         (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Add_IntInt_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APlayerController*                CallFunc_GetOwningPlayer_ReturnValue                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class UWidget*>                  CallFunc_GetAllChildren_ReturnValue                    (ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)
// class UWidget*                          CallFunc_Array_Get_Item                                (ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Array_Length_ReturnValue                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWBP_DeployMenu_SquadMemberListing_C*K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess                            (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_Less_IntInt_ReturnValue                       (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_BooleanAND_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_IsValid_ReturnValue                           (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_EqualEqual_ObjectObject_ReturnValue           (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::IsOwningPlayerInMemberWidgetList(bool* bOwnsMemberWidget, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, class UWidget* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class UWBP_DeployMenu_SquadMemberListing_C* K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing, bool K2Node_DynamicCast_bSuccess, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "IsOwningPlayerInMemberWidgetList");

	Params::WBP_DeployMenu_SquadList_C_IsOwningPlayerInMemberWidgetList Parms{};

	Parms.Temp_bool_True_if_break_was_hit_Variable = Temp_bool_True_if_break_was_hit_Variable;
	Parms.Temp_int_Array_Index_Variable = Temp_int_Array_Index_Variable;
	Parms.CallFunc_Not_PreBool_ReturnValue = CallFunc_Not_PreBool_ReturnValue;
	Parms.Temp_int_Loop_Counter_Variable = Temp_int_Loop_Counter_Variable;
	Parms.CallFunc_Add_IntInt_ReturnValue = CallFunc_Add_IntInt_ReturnValue;
	Parms.CallFunc_GetOwningPlayer_ReturnValue = CallFunc_GetOwningPlayer_ReturnValue;
	Parms.CallFunc_GetAllChildren_ReturnValue = std::move(CallFunc_GetAllChildren_ReturnValue);
	Parms.CallFunc_Array_Get_Item = CallFunc_Array_Get_Item;
	Parms.CallFunc_Array_Length_ReturnValue = CallFunc_Array_Length_ReturnValue;
	Parms.K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing = K2Node_DynamicCast_AsWBP_Deploy_Menu_Squad_Member_Listing;
	Parms.K2Node_DynamicCast_bSuccess = K2Node_DynamicCast_bSuccess;
	Parms.CallFunc_Less_IntInt_ReturnValue = CallFunc_Less_IntInt_ReturnValue;
	Parms.CallFunc_BooleanAND_ReturnValue = CallFunc_BooleanAND_ReturnValue;
	Parms.CallFunc_IsValid_ReturnValue = CallFunc_IsValid_ReturnValue;
	Parms.CallFunc_EqualEqual_ObjectObject_ReturnValue = CallFunc_EqualEqual_ObjectObject_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);

	CallFunc_GetAllChildren_ReturnValue = std::move(Parms.CallFunc_GetAllChildren_ReturnValue);

	if (bOwnsMemberWidget != nullptr)
		*bOwnsMemberWidget = std::move(Parms.bOwnsMemberWidget);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.SetupSQOptions
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bNoVisibleWidgets                                      (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
// enum class ESlateVisibility             Temp_byte_Variable                                     (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Temp_int_Array_Index_Variable                          (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Temp_int_Loop_Counter_Variable                         (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Add_IntInt_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// enum class ESlateVisibility             Temp_byte_Variable_1                                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class UWidget*>                  CallFunc_GetAllChildren_ReturnValue                    (ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)
// class UWidget*                          CallFunc_Array_Get_Item                                (ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_Array_Length_ReturnValue                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWBP_SQOption_C*                  K2Node_DynamicCast_AsWBP_SQOption                      (ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess                            (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_Less_IntInt_ReturnValue                       (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_NotEqual_ObjectObject_ReturnValue             (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_IsVisible_ReturnValue                         (ZeroConstructor, IsPlainOldData, NoDestructor)
// class UHorizontalBoxSlot*               CallFunc_SlotAsHorizontalBoxSlot_ReturnValue           (ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Temp_bool_Variable                                     (ZeroConstructor, IsPlainOldData, NoDestructor)
// enum class ESlateVisibility             K2Node_Select_Default                                  (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DeployMenu_SquadList_C::SetupSQOptions(bool bNoVisibleWidgets, enum class ESlateVisibility Temp_byte_Variable, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, enum class ESlateVisibility Temp_byte_Variable_1, TArray<class UWidget*>& CallFunc_GetAllChildren_ReturnValue, class UWidget* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class UWBP_SQOption_C* K2Node_DynamicCast_AsWBP_SQOption, bool K2Node_DynamicCast_bSuccess, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_NotEqual_ObjectObject_ReturnValue, bool CallFunc_IsVisible_ReturnValue, class UHorizontalBoxSlot* CallFunc_SlotAsHorizontalBoxSlot_ReturnValue, bool Temp_bool_Variable, enum class ESlateVisibility K2Node_Select_Default)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "SetupSQOptions");

	Params::WBP_DeployMenu_SquadList_C_SetupSQOptions Parms{};

	Parms.bNoVisibleWidgets = bNoVisibleWidgets;
	Parms.Temp_byte_Variable = Temp_byte_Variable;
	Parms.Temp_int_Array_Index_Variable = Temp_int_Array_Index_Variable;
	Parms.Temp_int_Loop_Counter_Variable = Temp_int_Loop_Counter_Variable;
	Parms.CallFunc_Add_IntInt_ReturnValue = CallFunc_Add_IntInt_ReturnValue;
	Parms.Temp_byte_Variable_1 = Temp_byte_Variable_1;
	Parms.CallFunc_GetAllChildren_ReturnValue = std::move(CallFunc_GetAllChildren_ReturnValue);
	Parms.CallFunc_Array_Get_Item = CallFunc_Array_Get_Item;
	Parms.CallFunc_Array_Length_ReturnValue = CallFunc_Array_Length_ReturnValue;
	Parms.K2Node_DynamicCast_AsWBP_SQOption = K2Node_DynamicCast_AsWBP_SQOption;
	Parms.K2Node_DynamicCast_bSuccess = K2Node_DynamicCast_bSuccess;
	Parms.CallFunc_Less_IntInt_ReturnValue = CallFunc_Less_IntInt_ReturnValue;
	Parms.CallFunc_NotEqual_ObjectObject_ReturnValue = CallFunc_NotEqual_ObjectObject_ReturnValue;
	Parms.CallFunc_IsVisible_ReturnValue = CallFunc_IsVisible_ReturnValue;
	Parms.CallFunc_SlotAsHorizontalBoxSlot_ReturnValue = CallFunc_SlotAsHorizontalBoxSlot_ReturnValue;
	Parms.Temp_bool_Variable = Temp_bool_Variable;
	Parms.K2Node_Select_Default = K2Node_Select_Default;

	UObject::ProcessEvent(Func, &Parms);

	CallFunc_GetAllChildren_ReturnValue = std::move(Parms.CallFunc_GetAllChildren_ReturnValue);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.HasAnySquadMembers
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    bValidMembersPresent                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_IsSquadValid_bValidSQ                         (ZeroConstructor, IsPlainOldData, NoDestructor)
// class AHDSquadState*                    CallFunc_GetSquadStateFromData_ReturnValue             (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CallFunc_GetNumSquadMembers_ReturnValue                (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_Greater_IntInt_ReturnValue                    (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::HasAnySquadMembers(bool* bValidMembersPresent, bool CallFunc_IsSquadValid_bValidSQ, class AHDSquadState* CallFunc_GetSquadStateFromData_ReturnValue, int32 CallFunc_GetNumSquadMembers_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "HasAnySquadMembers");

	Params::WBP_DeployMenu_SquadList_C_HasAnySquadMembers Parms{};

	Parms.CallFunc_IsSquadValid_bValidSQ = CallFunc_IsSquadValid_bValidSQ;
	Parms.CallFunc_GetSquadStateFromData_ReturnValue = CallFunc_GetSquadStateFromData_ReturnValue;
	Parms.CallFunc_GetNumSquadMembers_ReturnValue = CallFunc_GetNumSquadMembers_ReturnValue;
	Parms.CallFunc_Greater_IntInt_ReturnValue = CallFunc_Greater_IntInt_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);

	if (bValidMembersPresent != nullptr)
		*bValidMembersPresent = std::move(Parms.bValidMembersPresent);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.UpdateLockUnlockBtnState
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Temp_bool_Variable                                     (ZeroConstructor, IsPlainOldData, NoDestructor)
// class FText                             Temp_text_Variable                                     ()
// class FText                             Temp_text_Variable_1                                   ()
// class AHDSquadState*                    CallFunc_GetSquadStateFromData_ReturnValue             (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             K2Node_Select_Default                                  ()

void UWBP_DeployMenu_SquadList_C::UpdateLockUnlockBtnState(bool Temp_bool_Variable, class FText Temp_text_Variable, class FText Temp_text_Variable_1, class AHDSquadState* CallFunc_GetSquadStateFromData_ReturnValue, class FText K2Node_Select_Default)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "UpdateLockUnlockBtnState");

	Params::WBP_DeployMenu_SquadList_C_UpdateLockUnlockBtnState Parms{};

	Parms.Temp_bool_Variable = Temp_bool_Variable;
	Parms.Temp_text_Variable = Temp_text_Variable;
	Parms.Temp_text_Variable_1 = Temp_text_Variable_1;
	Parms.CallFunc_GetSquadStateFromData_ReturnValue = CallFunc_GetSquadStateFromData_ReturnValue;
	Parms.K2Node_Select_Default = K2Node_Select_Default;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.WasListCollapsedByUser
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    Param_bCollapsedByUser                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::WasListCollapsedByUser(bool* Param_bCollapsedByUser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "WasListCollapsedByUser");

	Params::WBP_DeployMenu_SquadList_C_WasListCollapsedByUser Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_bCollapsedByUser != nullptr)
		*Param_bCollapsedByUser = std::move(Parms.Param_bCollapsedByUser);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.KickSquadMember
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHDPlayerState*                   MemberPSToKick                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AHDSquadState*                    CallFunc_GetSquadStateFromData_ReturnValue             (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsOwningPlayerRegisteredSquadLeader_bSquadLeader(ZeroConstructor, IsPlainOldData, NoDestructor)
// class APlayerController*                CallFunc_GetOwningPlayer_ReturnValue                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AHDSquadState*                    CallFunc_GetSquadStateFromData_ReturnValue_1           (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_HDPlayerControllerBase_C*     K2Node_DynamicCast_AsBP_HDPlayer_Controller_Base       (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess                            (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_IsRegisteredSquadMember_ReturnValue           (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_BooleanAND_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_KickSquadMember_bRemoveSuccess                (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::KickSquadMember(class AHDPlayerState* MemberPSToKick, class AHDSquadState* CallFunc_GetSquadStateFromData_ReturnValue, bool CallFunc_IsOwningPlayerRegisteredSquadLeader_bSquadLeader, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, class AHDSquadState* CallFunc_GetSquadStateFromData_ReturnValue_1, class ABP_HDPlayerControllerBase_C* K2Node_DynamicCast_AsBP_HDPlayer_Controller_Base, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsRegisteredSquadMember_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_KickSquadMember_bRemoveSuccess)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "KickSquadMember");

	Params::WBP_DeployMenu_SquadList_C_KickSquadMember Parms{};

	Parms.MemberPSToKick = MemberPSToKick;
	Parms.CallFunc_GetSquadStateFromData_ReturnValue = CallFunc_GetSquadStateFromData_ReturnValue;
	Parms.CallFunc_IsOwningPlayerRegisteredSquadLeader_bSquadLeader = CallFunc_IsOwningPlayerRegisteredSquadLeader_bSquadLeader;
	Parms.CallFunc_GetOwningPlayer_ReturnValue = CallFunc_GetOwningPlayer_ReturnValue;
	Parms.CallFunc_GetSquadStateFromData_ReturnValue_1 = CallFunc_GetSquadStateFromData_ReturnValue_1;
	Parms.K2Node_DynamicCast_AsBP_HDPlayer_Controller_Base = K2Node_DynamicCast_AsBP_HDPlayer_Controller_Base;
	Parms.K2Node_DynamicCast_bSuccess = K2Node_DynamicCast_bSuccess;
	Parms.CallFunc_IsRegisteredSquadMember_ReturnValue = CallFunc_IsRegisteredSquadMember_ReturnValue;
	Parms.CallFunc_BooleanAND_ReturnValue = CallFunc_BooleanAND_ReturnValue;
	Parms.CallFunc_KickSquadMember_bRemoveSuccess = CallFunc_KickSquadMember_bRemoveSuccess;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.LockSquad
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_DeployMenu_SquadList_C::LockSquad()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "LockSquad");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.UnlockSquad
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_DeployMenu_SquadList_C::UnlockSquad()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "UnlockSquad");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.SetSquadLockedState
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bNewLocked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class AHDSquadState*                    CallFunc_GetSquadStateFromData_ReturnValue             (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AHDSquadState*                    CallFunc_GetSquadStateFromData_ReturnValue_1           (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APlayerController*                CallFunc_GetOwningPlayer_ReturnValue                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_NotEqual_BoolBool_ReturnValue                 (ZeroConstructor, IsPlainOldData, NoDestructor)
// class ABP_HDPlayerControllerBase_C*     K2Node_DynamicCast_AsBP_HDPlayer_Controller_Base       (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess                            (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_IsOwningPlayerRegisteredSquadLeader_bSquadLeader(ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_BooleanAND_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::SetSquadLockedState(bool bNewLocked, class AHDSquadState* CallFunc_GetSquadStateFromData_ReturnValue, class AHDSquadState* CallFunc_GetSquadStateFromData_ReturnValue_1, class APlayerController* CallFunc_GetOwningPlayer_ReturnValue, bool CallFunc_NotEqual_BoolBool_ReturnValue, class ABP_HDPlayerControllerBase_C* K2Node_DynamicCast_AsBP_HDPlayer_Controller_Base, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsOwningPlayerRegisteredSquadLeader_bSquadLeader, bool CallFunc_BooleanAND_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "SetSquadLockedState");

	Params::WBP_DeployMenu_SquadList_C_SetSquadLockedState Parms{};

	Parms.bNewLocked = bNewLocked;
	Parms.CallFunc_GetSquadStateFromData_ReturnValue = CallFunc_GetSquadStateFromData_ReturnValue;
	Parms.CallFunc_GetSquadStateFromData_ReturnValue_1 = CallFunc_GetSquadStateFromData_ReturnValue_1;
	Parms.CallFunc_GetOwningPlayer_ReturnValue = CallFunc_GetOwningPlayer_ReturnValue;
	Parms.CallFunc_NotEqual_BoolBool_ReturnValue = CallFunc_NotEqual_BoolBool_ReturnValue;
	Parms.K2Node_DynamicCast_AsBP_HDPlayer_Controller_Base = K2Node_DynamicCast_AsBP_HDPlayer_Controller_Base;
	Parms.K2Node_DynamicCast_bSuccess = K2Node_DynamicCast_bSuccess;
	Parms.CallFunc_IsOwningPlayerRegisteredSquadLeader_bSquadLeader = CallFunc_IsOwningPlayerRegisteredSquadLeader_bSquadLeader;
	Parms.CallFunc_BooleanAND_ReturnValue = CallFunc_BooleanAND_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.IsSquadValid
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    bValidSQ                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class AHDSquadState*                    CallFunc_GetSquadStateFromData_ReturnValue             (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsValid_ReturnValue                           (ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DeployMenu_SquadList_C::IsSquadValid(bool* bValidSQ, class AHDSquadState* CallFunc_GetSquadStateFromData_ReturnValue, bool CallFunc_IsValid_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "IsSquadValid");

	Params::WBP_DeployMenu_SquadList_C_IsSquadValid Parms{};

	Parms.CallFunc_GetSquadStateFromData_ReturnValue = CallFunc_GetSquadStateFromData_ReturnValue;
	Parms.CallFunc_IsValid_ReturnValue = CallFunc_IsValid_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);

	if (bValidSQ != nullptr)
		*bValidSQ = std::move(Parms.bValidSQ);
}


// Function WBP_DeployMenu_SquadList.WBP_DeployMenu_SquadList_C.OnPaint
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// struct FPaintContext                    Context                                                (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UWBP_DeployMenu_SquadList_C::OnPaint(struct FPaintContext& Context) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DeployMenu_SquadList_C", "OnPaint");

	Params::WBP_DeployMenu_SquadList_C_OnPaint Parms{};

	Parms.Context = std::move(Context);

	UObject::ProcessEvent(Func, &Parms);

	Context = std::move(Parms.Context);
}

}

