#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HDRadialMenuBase

#include "Basic.hpp"

#include "InputCore_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_HDRadialMenuBase.WBP_HDRadialMenuBase_C
// 0x0048 (0x0278 - 0x0230)
class UWBP_HDRadialMenuBase_C : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0230(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	FMulticastInlineDelegateProperty_             SubmenuCommit;                                     // 0x0238(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<struct FKey>                           SubmitKeys;                                        // 0x0248(0x0010)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TArray<struct FKey>                           BackKeys;                                          // 0x0258(0x0010)(Edit, BlueprintVisible, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             Cancel;                                            // 0x0268(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void SubmenuCommit__DelegateSignature(class FName Category, class FName SubItem);
	void Cancel__DelegateSignature();
	void ExecuteUbergraph_WBP_HDRadialMenuBase(int32 EntryPoint);
	void GoBack();
	void Submit();
	struct FEventReply OnMouseButtonDown(const struct FGeometry& MyGeometry, struct FPointerEvent& MouseEvent, const struct FEventReply& CallFunc_Handled_ReturnValue);
	struct FEventReply OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent, const struct FEventReply& CallFunc_Unhandled_ReturnValue, const struct FKey& CallFunc_GetKey_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, bool CallFunc_Array_Contains_ReturnValue_1, const struct FEventReply& CallFunc_Handled_ReturnValue);
	struct FEventReply OnMouseButtonDoubleClick(const struct FGeometry& InMyGeometry, struct FPointerEvent& InMouseEvent, const struct FEventReply& CallFunc_Handled_ReturnValue);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"WBP_HDRadialMenuBase_C">();
	}
	static class UWBP_HDRadialMenuBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_HDRadialMenuBase_C>();
	}
};

}

